Добавление в курс по питону практического задания "Утилита tree"
senjun-team/senjun-courses pull request #140
Opened 2024-08-03 06:25 UTC by Microvenator

2024-08-03 11:27 UTC, alexey-zakharenkov requested changes

2024-08-03 11:27 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/data.json
> +}
No LF at the end of file.

2024-08-03 11:27 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
> +    │   ├──  Edward Scissorhands.avi
Лишний пробел перед словом "Edward"

2024-08-03 11:27 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
> +Для отображения в консоли дерева директорий скопируйте в проект Unicode-символы псевдографики: `│   `, `├─`, `└──`.
За символом вертикальной черты следуют два неразрывных пробела и один обычный. Может я не вполне понимаю, зачем так сделано, но обычный пробел явно лишний, т.к. приводит к эффекту переноса запятой на новую строку.

2024-08-03 11:27 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
> +Вы можете запускать скрипт tree.py с разными аргументами командной строки и проверять вывод на различных директориях. Для этого есть кнопка «Запустить» и поле для ввода аргументов. Для удобства тести
Не надо ли пути вроде tree.py и т.д. оформить как код?

2024-08-03 11:27 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/hint.md
> +Для того, чтобы получить директории и файлы в алфавитном порядке, примените встроенную функцию `sorted()`: `sorted(Path(cur_dir).iterdir())`.
"Для того чтобы" - составной союз, в данном месте не дробится запятой.

2024-08-03 15:41 UTC, Microvenator commented on python/practice/python_tree_util/data.json
> +}
fixed

2024-08-03 15:42 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +    │   ├──  Edward Scissorhands.avi
Да, спасибо. Случайно попал, когда был в имени файла настоящего файла.

2024-08-03 15:43 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +Для отображения в консоли дерева директорий скопируйте в проект Unicode-символы псевдографики: `│   `, `├─`, `└──`.
Вообще здесь не должно быть пробелов, только сам символ псевдографики. Исправила.

2024-08-03 15:44 UTC, Microvenator commented on python/practice/python_tree_util/hint.md
> +Для того, чтобы получить директории и файлы в алфавитном порядке, примените встроенную функцию `sorted()`: `sorted(Path(cur_dir).iterdir())`.
Да, точно. Исправлено)

2024-08-03 22:43 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project/test_tree.py
> +    def test_data(self):
Может, дать более говорящие названия?
test_data => test_tree_py / test_tree_script
check => check_case

2024-08-03 22:43 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project/tree.py
> +"""
LF

2024-08-03 22:43 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project/utils.py
> +"""
LF

2024-08-03 22:43 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +    count_dirs += 1
1. Функция, занимающая форматированием результата, не должна заниматься  вычислениями. Лучше, чтобы функция traverse сразу отдала скорректированное значение.

2. "count_dirs" переводится как "посчитать директории", dir_count - "количество директорий"

2024-08-03 22:43 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +def show_tree(dir, dir_only, level):
dir**s**_only?

2024-08-03 22:43 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +        is_dir = os.path.isdir(path)
У всех используемых здесь методов из os.path есть свои аналоги в pathlib. Лучше не смешивать две библиотеки, если можно обойтись одной.
https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module

2024-08-03 22:43 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
> +`pathlib` — обход директории. [Документация.](https://docs.python.org/3/library/pathlib.html)
Обход директории можно сделать и через os.listdir(), так же как и работать с путями и свойствами файлов/директорий можно в pathlib. Лучше не предлагать две библиотеки.

2024-08-04 06:08 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +Вы можете запускать скрипт tree.py с разными аргументами командной строки и проверять вывод на различных директориях. Для этого есть кнопка «Запустить» и поле для ввода аргументов. Для удобства тести
Сделала

2024-08-04 06:15 UTC, Microvenator commented
Ревью от разработчика в tg:

> Рефакторить код без типов, конечно больно)
> 
> Все использование os устаревшее. У Path есть методы is_file() и is_dir(). os.path.join() тоже уже не нужен
> if is_dir or not dir_only and path.is_file()
> 
> Ну и конечно символы лучше положить в Enum, а не хардкодить.

2024-08-04 06:16 UTC, Microvenator commented
Ревью от разработчика в tg:

> - в файле utils.py в стр 69 я бы все-такие через f-строку передал аргумент, они вроде-как предпочтительнее)
> - в том же файле в стр 60, 72 и возможно даже 57, я бы расставил скобки для читаемости, особенно, учитывая, что это для новичков. Но это чисто мое виденье.

2024-08-04 07:13 UTC, Microvenator commented on python/practice/python_tree_util/project/test_tree.py
> +    def test_data(self):
Да, так лучше. Готово

2024-08-04 07:27 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/utils.py
> +    count_dirs += 1
1. Принято. Исправлено.
2. Кажется, названия переменных по дефолту воспринимаются как существительные, а не глаголы. Поэтому можно нарушить правила языка, чтобы было проще читать код. Здесь у двух переменных одинаковый префикс count, и они сразу воспринимаются как счетчики. Из этой же серии btn_decline вместо decline_btn, style_light, style_dark, style_contrast и тд.

2024-08-04 07:27 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +# Пробел и символы псевдографики для изображения в консоли
Сделать doc-string'ом класса?

2024-08-04 07:27 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
>  `pathlib` — обход директории. [Документация.](https://docs.python.org/3/library/pathlib.html)
"обход директории" теперь неполно описывает полезность библиотеки для данного проекта. Предлагаю "работа с путями и файлам".

2024-08-04 07:29 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/utils.py
> +def show_tree(dir, dir_only, level):
Вообще практикуется и такое и такое название, но твой вариант определенно более понятный. Заменила.

http://tinco.pair.com/bhaskar/gtm/doc/books/mr/manual/DIRONLY.html
https://docs.adacore.com/live/wave/gtkada/html/gtkada_rm/docs/gtkada__file_selection___spec.html
https://graylab.jhu.edu/PyRosetta.documentation/pyrosetta.rosetta.basic.database.html

2024-08-04 07:33 UTC, Microvenator commented on python/practice/python_tree_util/project/test_tree.py
> +            ("dir without args", FULL_DIR, ["test_data"]),
Тут все сложно)) У меня был пограничный тест. И на нем текущий вариан решения вывел:

```
1 directory, 0 files
```

Мне кажется, что это логично. Потому что мы всегда при подсчете учитываем директорию, с которой начат обход.

Но тулза tree, которая присутствует в репах многих линукс-дистрибутивов, считает иначе:

```
0 directories, 0 files
```

При этом в остальных случаях ее вывод соответствует выводу tree.py. То ли tree себя неконсистентно ведет, то ли я чего-то не понимаю.

2024-08-04 07:34 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/utils.py
> +        is_dir = os.path.isdir(path)
Убрала из текста, из подсказки и из кода модуль os. Везде остался pathlib.

2024-08-04 07:34 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +`pathlib` — обход директории. [Документация.](https://docs.python.org/3/library/pathlib.html)
Решила вместо os везде оставить pathlib.

2024-08-04 07:42 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/utils.py
> +# Пробел и символы псевдографики для изображения в консоли
Готово

2024-08-04 07:43 UTC, Microvenator commented on python/practice/python_tree_util/text.md
>  `pathlib` — обход директории. [Документация.](https://docs.python.org/3/library/pathlib.html)
Да, взяла твое описание

2024-08-04 07:44 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
> +Необходимо написать консольную утилиту, которая показывает содержимое директории в виде дерева и выводит, сколько в ней директорий и файлов. Файлы и директории должны следовать в алфавитном порядке.
Тут неточность в формулировке касаемо учёта корневой директории. Вернее будет "количество найденных директорий и файлов".

2024-08-04 09:30 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +Необходимо написать консольную утилиту, которая показывает содержимое директории в виде дерева и выводит, сколько в ней директорий и файлов. Файлы и директории должны следовать в алфавитном порядке.
Переформулировала пару предложений.

2024-08-04 18:35 UTC, alexey-zakharenkov commented
Тесты не проходят.
Во-первых, имена типа FULL_DIR определены ниже точки обращения. Во-вторых, ожидается пустая директория movies/historical, но в гит-репозитории такой нет.

Думаю, тесты должны быть составлены так, чтобы любознательный студент мог их самостоятельно запустить без большой головной боли.

2024-08-04 23:37 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +    return count_dirs, count_files
Рекурсия на дереве прекрасна тем, что вызов её от любого узла подобен вызову от любого другого узла на любом уровне. Текущая реализация рекурсивного обхода лишена этой красоты:
1. Вызов от первой директории существенно отличается от последующих вызовов. В частности, вывод названия целевой директории делается отдельным вызовом `print(dir)`, для поддиректорий же делается другой вызов.
2. Подсчёт целевой директории делается отдельным вызовом `count_dirs += 1`, остальные директории учитываются в другом месте.

В итоге получилось расползание одних и тех же действий по разным местам в коде, а функции show_tree и traverse имеют перекрывающиеся обязанности по консольному выводу и подсчёту.

Я переписал эти функции так, что функция show_tree сама не занимается выводом дерева и подсчётом. Вывод каждого названия директории делается в одном месте. Учёт каждой директории делается в одном месте. К сожалению, из-за того что первая директория должна быть напечатана в точности так, как указана в аргументах команды (не просто "test_data", а, например, "./test_data"), первый вызов traverse приходится отличать от последующих ценой отклонения от полного подобия.

```suggestion
def show_tree(dir, dirs_only, level):
    """
    Обходит директорию dir для вывода в консоль ее древовидной
    структуры, а также количества найденных директорий и файлов.

    Флаг dirs_only означает, что обрабатывать файлы не надо.
    level - это целое число либо None. Указывает, до какого уровня
    вложенности отображать иерархию.
    """

    levels = -1 if level is None else level
    count_dirs, count_files = traverse(dir, levels, "", dirs_only)

    print(f"\n{dir_str(count_dirs)}{file_str(count_files, dirs_only)}")


def dir_str(count_dirs):
    d = "directory" if count_dirs == 1 else "directories"
    return f"{count_dirs} {d}"


def file_str(count_files, dirs_only):
    if dirs_only:
        return ""

    f = "file" if count_files == 1 else "files"
    return f", {count_files} {f}"


def traverse(cur_dir, levels, prefix, dirs_only):
    """
    Рекурсивно обходит директорию cur_dir.
    Целое число levels нужно, чтобы завершить обход при заданном уровне вложенности.
    Строка prefix необходима, чтобы перед именем директории или файла вывести
    символы псевдографики для изображения древовидной иерархии.
    Флаг dirs_only означает, что нужно обрабатывать только директории (не файлы).

    Функция возвращает количество выведенных в консоль директорий и файлов.
    """

    print(f"{cur_dir if isinstance(cur_dir, str) else cur_dir.name}")

    count_dirs = 1  # count cur_dir
    count_files = 0

    if levels == 0:
        return count_dirs, count_files

    contents = sorted(Path(cur_dir).iterdir())

    for i, path in enumerate(contents):
        is_last = i == len(contents) - 1

        if dirs_only and path.is_file():
            continue

        print(f"{prefix}{symbol_trailing(is_last)} ", end="")

        if path.is_file():
            print(path.name)
            count_files += 1
        elif path.is_dir():
            count_dirs_in_subtree, count_files_in_subtree = traverse(
                path,
                levels - 1,
                f"{prefix}{symbols_indent(is_last)}",
                dirs_only,
            )
            count_dirs += count_dirs_in_subtree
            count_files += count_files_in_subtree

    return count_dirs, count_files
```

2024-08-05 06:26 UTC, Microvenator commented
> Тесты не проходят. Во-первых, имена типа FULL_DIR определены ниже точки обращения. 

Исправлено. Удивительно, но локально c python 3.11.9 ошибки не было.

> Во-вторых, ожидается пустая директория movies/historical, но в гит-репозитории такой нет.

Забыла, что в гите нельзя без приседаний держать пустые директории. Бай дизайн:
https://archive.kernel.org/oldwiki/git.wiki.kernel.org/index.php/GitFaq.html#Can_I_add_empty_directories.3F

Добавила создание и удаление пустой директории в setUp и tearDown в юнит-тестах.

> Думаю, тесты должны быть составлены так, чтобы любознательный студент мог их самостоятельно запустить без большой головной боли.

Да, так и должно быть. В интерфейсе страницы с практикой будет кнопка "Отправить на проверку". Она по сути будет дергать `python3 -m unittest`, который подхватит test_tree.py в корне проекта. Который в свою очередь доступен пользователям.

![image](https://github.com/user-attachments/assets/46f13d84-f82a-4bcc-9790-0150037cf354)

2024-08-05 07:52 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
>          is_last = i == len(contents) - 1
Нашёл баг.
Даже когда файлы игнорируются, они участвуют в вычислении is_last. Чтобы увидеть проблему, советую создать файл `test_data/movies/fantasy/Time Bandits.avi` и вызвать tree.py с опцией -d.

2024-08-05 07:52 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
>      │   └── LOTR
В файле text.md в примерах вывода присутствуют неразрывные пробелы. Лучше заменить на обычные, а то вдруг этот текст будут копировать, например для создания plan_output для новых тестов.
<img width="200" alt="Снимок экрана 2024-08-05 в 10 49 45" src="https://github.com/user-attachments/assets/c25fbace-2cda-476d-aa5e-9344c9ab26bf">

2024-08-05 10:26 UTC, Microvenator commented on python/practice/python_tree_util/text.md
>      │   └── LOTR
Да, ты прав. Заменила

2024-08-05 10:26 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/utils.py
>          is_last = i == len(contents) - 1
Пофиксила, добавила тестов.

2024-08-05 10:46 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
>  Запуск утилиты с указанием пути `./test_data/` и опцией для отображения только директорий:
Путь `./test_data/` теперь не соответствует тому, что указано в команде.

2024-08-05 16:15 UTC, Microvenator commented on python/practice/python_tree_util/text.md
>  Запуск утилиты с указанием пути `./test_data/` и опцией для отображения только директорий:
Ну тут подразумевалось, что это же одно и тоже, и в тексте можно так писать, а в коде - эдак. Но да, лучше четко указывать. Пофиксила

2024-08-06 07:32 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +        return (p for p in Path(dir).iterdir() if p.is_dir())
Генераторы даются в 23-й главе, компрехеншены - в 24-й. Если быть методически последовательным, то надо делать через циклы.

2024-08-06 10:06 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/utils.py
> +        return (p for p in Path(dir).iterdir() if p.is_dir())
Да. А предложенный тобой `["python3", "tree.py", *args]` вообще в 25-й главе про распаковку и упаковку. Поэтому я подвинула эту практику - теперь она после 25 главы. 

Сейчас в процессе подготовки другие практические задания. "Калькулятор алгебраических выражений", кажется, вполне может идти сразу после главы 15. Еще будут задания на классы и на asyncio.

2024-08-06 11:08 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +        return (p for p in Path(dir).iterdir() if p.is_dir())
Распаковка через `*` используется в тестирующем модуле, там много непройденных тем, хотя бы само тестирование. Разница в том, что студент не должен досконально разбираться в этом модуле.

А практика привязана к главам? Я как раз думал, что это практическое задание на тему "модули", поэтому и относилось к 20-й главе. В принципе материала достаточно, чтобы можно было предложить её на данном этапе. Только тогда в авторском решении не надо забегать вперёд.

2024-08-06 15:12 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/utils.py
> +        return (p for p in Path(dir).iterdir() if p.is_dir())
>  Разница в том, что студент не должен досконально разбираться в этом модуле.

Именно. Но единственное, чего мне хочется от тестов - чтобы пользователю было понятно, с какими аргументами какой код тестируется. И как при желании изменить/дополнить список тест-кейсов. Поэтому лучше бы пользователю строчку с подготовкой аргументов все-таки понимать)

> А практика привязана к главам? Я как раз думал, что это практическое задание на тему "модули", поэтому и относилось к 20-й главе. 

Практическое задание не привязано к конкретной главе, но появляется в тот момент, когда теории становится достаточно, чтобы выполнить его без особых костылей. Это такой майлстоун.

2024-08-07 12:26 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +python3 tree.py [options] [dir]
Привела к единообразию.

2024-08-07 12:27 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +`dir` — директория, содержимое которой необходимо отобразить. Если не указана, работать с текущей директорией.
Досыпала тестов.

2024-08-07 12:27 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +    │   │   ├── The Fellowship of the Ring.avi
Обновила пример.

2024-08-07 12:28 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +Вы можете запускать скрипт `tree.py` с разными аргументами командной строки и проверять вывод на различных директориях. Для этого есть кнопка «Запустить» и поле для ввода аргументов. Для удобства тес
Дописала про текущую директорию. 

Директории могут быть какими угодно. Пользователи обожают лазить по нашей фс в контейнере...) Можно смотреть хоть корень, хоть домашнюю директорию пользователя. Это не страшно, потому что прав для того, чтобы что-то повредить, у пользователя нет.

2024-08-07 13:38 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project/test_tree.py
> +def run_tree_util(util_path, args):
Можно не вводить параметр `util_path`.

`tree.py` лежит рядом с `test_tree.py`, значит полный путь к нему всегда можно получить как
`Path(__file__).parent / "tree.py"`

2024-08-07 13:38 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/text.md
> +Вы можете запускать скрипт `tree.py` с разными аргументами командной строки и проверять вывод на различных директориях. Для этого есть кнопка «Запустить» и поле для ввода аргументов. Для удобства тес
Опечатка в слове директор**я**.

FYI, язык разметки Markdown, подобно HTML, заменяет один или несколько подряд идущих пробельных символов одним пробелом (есть исключения типа \n\n). Это позволяет не делать абзац из нескольких предложений очень длинной строкой, а разбить его на несколько строк шириной ~100 символов. Дифы компактней получаются, а дописанное в конец абзаца предложение не затрагивает уже написанных предложений.

2024-08-08 07:08 UTC, Microvenator commented on python/practice/python_tree_util/project/test_tree.py
> +def run_tree_util(util_path, args):
Да, спасибо большое! Так лучше

2024-08-08 08:00 UTC, Microvenator commented on python/practice/python_tree_util/text.md
> +Вы можете запускать скрипт `tree.py` с разными аргументами командной строки и проверять вывод на различных директориях. Для этого есть кнопка «Запустить» и поле для ввода аргументов. Для удобства тес
Опечатку поправила.

Насчет того, как удобнее писать текст в md - да, можно и разбивать абзацы на строки. Но гитхаб и гитлаб, кажется, уже довольно давно умеют подсвечивать дифф внутри одной строки.

2024-08-08 20:43 UTC, khva submitted a review, later dismissed

2024-08-09 06:54 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project/test_tree.py
> +            ("dir with -d", FULL_DIR_DIR_ONLY, ["-d", "./test_data/"]),
DIR**S**_ONLY.
(Такое написание уже используется в одном из тестов.)

2024-08-09 06:54 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +    данный файл/директория последним внутри родительской директории.
"данный файл/директория последний", конечно, коробит мой въедливый мозг.

Согласно нормам великого и могучего, определение при однородных разнородных (в смысле, разного рода) членах согласуется с ближайшим существительным. Т.е. правильно "данный файл/директория" и "файл/директория последняя". Но когда два определения стоят по разные стороны, это шах и пат. Предлагаю "является ли данный файл (директория) последним".

2024-08-09 12:49 UTC, Microvenator commented on python/practice/python_tree_util/project_solution/tree.py
> +            f"{raw_val} is an invalid value for level. It must be greater or equal to 1"
поправила

2024-08-09 19:51 UTC, alexey-zakharenkov approved these changes

2024-08-10 08:31 UTC, khva approved these changes

2024-08-10 08:37 UTC, merged

2024-08-13 16:16 UTC, stanislav-tsaplev commented on python/practice/python_tree_util/project_solution/utils.py
> +def show_tree(dir, dir_only, level):
Возможно, это вкусовщина, но лично мне коробит взгляд несимметричность и неуниверсальность: почему dirs_only есть, а files_only нет? Если бы я писал решение, я бы спроектировал `show_tree` так: `show_tree(dir, consider_dirs=true, consider_files=true, level=None)`.

2024-08-14 07:02 UTC, alexey-zakharenkov commented on python/practice/python_tree_util/project_solution/utils.py
> +def show_tree(dir, dir_only, level):
Утилита с названием `tree` строит дерево. Можно построить дерево директорий без файлов, но нельзя построить дерево файлов без директорий. При этом в дереве будет хотя бы одна директория - dir.